
val foodImages = mapOf(
    // === RICE DISHES ===
    "Nasi Goreng" to "https://images.pexels.com/photos/19566419/pexels-photo-19566419.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Nasi Putih" to "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Nasi Uduk" to "https://images.pexels.com/photos/5638527/pexels-photo-5638527.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Nasi Kuning" to "https://upload.wikimedia.org/wikipedia/commons/2/28/Nasi_kuning_tumpeng.jpg",
    "Nasi Padang" to "https://upload.wikimedia.org/wikipedia/commons/9/97/Nasi_Padang_Sederhana.jpg",
    "Bubur Ayam" to "https://images.pexels.com/photos/6646351/pexels-photo-6646351.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Lontong Sayur" to "https://upload.wikimedia.org/wikipedia/commons/b/b5/Lontong_sayur_Betawi.JPG",

    // === MEAT DISHES ===
    "Rendang" to "https://images.pexels.com/photos/5409015/pexels-photo-5409015.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Sate Ayam" to "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Ayam Goreng" to "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Ayam Geprek" to "https://upload.wikimedia.org/wikipedia/commons/e/e5/Ayam_geprek.jpg",
    "Ayam Bakar" to "https://images.pexels.com/photos/6210959/pexels-photo-6210959.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Opor Ayam" to "https://upload.wikimedia.org/wikipedia/commons/4/4c/Lontong_Opor.jpg",
    "Bebek Goreng" to "https://upload.wikimedia.org/wikipedia/commons/8/86/Bebek_Goreng_Kremes.jpg",
    "Ikan Bakar" to "https://images.pexels.com/photos/3296279/pexels-photo-3296279.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Ikan Goreng" to "https://images.pexels.com/photos/8963473/pexels-photo-8963473.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === SOUPS ===
    "Soto Ayam" to "https://images.pexels.com/photos/6646350/pexels-photo-6646350.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Soto Betawi" to "https://upload.wikimedia.org/wikipedia/commons/9/96/Soto_Betawi_Jakarta.JPG",
    "Bakso" to "https://images.pexels.com/photos/6646354/pexels-photo-6646354.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Rawon" to "https://upload.wikimedia.org/wikipedia/commons/3/3a/Rawon_Setan_Surabaya.jpg",
    "Sop Buntut" to "https://upload.wikimedia.org/wikipedia/commons/1/1e/Sop_Buntut_Bogor.jpg",

    // === NOODLES ===
    "Mie Goreng" to "https://images.pexels.com/photos/6646071/pexels-photo-6646071.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Mie Ayam" to "https://upload.wikimedia.org/wikipedia/commons/9/91/Mie_Ayam_Bakso_Dumpling.jpg",
    "Indomie Goreng" to "https://upload.wikimedia.org/wikipedia/commons/2/23/Indomie_Goreng_Jumbo.jpg",
    "Indomie Kuah" to "https://upload.wikimedia.org/wikipedia/commons/6/6d/Indomie_Soto_Mie.jpg",
    "Kwetiau Goreng" to "https://upload.wikimedia.org/wikipedia/commons/4/4e/Kwetiau_Goreng_Sapi.JPG",

    // === VEGETABLES ===
    "Gado-Gado" to "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Sayur Asem" to "https://upload.wikimedia.org/wikipedia/commons/5/5e/Sayur_Asem.jpg",
    "Sayur Lodeh" to "https://upload.wikimedia.org/wikipedia/commons/4/40/Sayur_Lodeh.jpg",
    "Capcay" to "https://upload.wikimedia.org/wikipedia/commons/8/87/Cap_Cay_Kuah.jpg",
    "Tumis Kangkung" to "https://upload.wikimedia.org/wikipedia/commons/2/22/Cah_Kangkung.jpg",
    "Pecel" to "https://upload.wikimedia.org/wikipedia/commons/6/6f/Nasi_Pecel.jpg",
    "Urap" to "https://upload.wikimedia.org/wikipedia/commons/2/22/Urap_Jawa.jpg",
    "Lalapan" to "https://upload.wikimedia.org/wikipedia/commons/3/34/Lalapan_Sunda.jpg",

    // === TOFU/TEMPE ===
    "Tempe Goreng" to "https://images.pexels.com/photos/6646067/pexels-photo-6646067.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Tahu Goreng" to "https://upload.wikimedia.org/wikipedia/commons/c/c8/Tahu_goreng.jpg",
    "Tahu Isi" to "https://upload.wikimedia.org/wikipedia/commons/8/8b/Tahu_isi_Semarang.JPG",
    "Tempe Mendoan" to "https://upload.wikimedia.org/wikipedia/commons/e/e0/Tempe_Mendoan_Satu.jpg",
    "Perkedel" to "https://upload.wikimedia.org/wikipedia/commons/7/7b/Perkedel_kentang.JPG",

    // === SNACKS ===
    "Gorengan" to "https://upload.wikimedia.org/wikipedia/commons/e/e0/Gorengan.JPG",
    "Martabak Manis" to "https://images.pexels.com/photos/14102377/pexels-photo-14102377.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Martabak Telur" to "https://upload.wikimedia.org/wikipedia/commons/8/82/Martabak_Telur.jpg",
    "Risol" to "https://upload.wikimedia.org/wikipedia/commons/e/e1/Risoles.jpg",
    "Pisang Goreng" to "https://images.pexels.com/photos/6646067/pexels-photo-6646067.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Pempek" to "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pempek_Palembang.jpg",
    "Ketoprak" to "https://upload.wikimedia.org/wikipedia/commons/1/1a/Ketoprak_Jakarta.JPG",
    "Bakwan" to "https://upload.wikimedia.org/wikipedia/commons/0/01/Bakwan_jagung.JPG",
    "Tahu Sumedang" to "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tahu_Sumedang.jpg",
    "Tempe Kemul" to "https://upload.wikimedia.org/wikipedia/commons/1/1f/Tempe_Kemul_Wonosobo.jpg",
    "Cireng" to "https://upload.wikimedia.org/wikipedia/commons/8/8a/Cireng.jpg",
    "Combro" to "https://upload.wikimedia.org/wikipedia/commons/3/36/Combro.jpg",
    "Misro" to "https://upload.wikimedia.org/wikipedia/commons/f/f6/Misro.JPG",
    "Gehu" to "https://upload.wikimedia.org/wikipedia/commons/e/e9/Gehu_Pedas.jpg",
    "Ote-ote" to "https://upload.wikimedia.org/wikipedia/commons/4/4b/Ote-ote_Porong.jpg",
    "Bala-bala" to "https://upload.wikimedia.org/wikipedia/commons/9/98/Bala-bala.JPG",
    "Sukun Goreng" to "https://upload.wikimedia.org/wikipedia/commons/5/52/Sukun_goreng.jpg",
    "Martabak Telor Spesial" to "https://upload.wikimedia.org/wikipedia/commons/d/d6/Martabak_Kubang_Hayati.jpg",
    "Martabak Manis Coklat" to "https://images.pexels.com/photos/14102377/pexels-photo-14102377.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Martabak Manis Keju" to "https://upload.wikimedia.org/wikipedia/commons/5/51/Martabak_Keju.jpg",
    "Lumpia Semarang" to "https://upload.wikimedia.org/wikipedia/commons/4/41/Lumpia_Semarang.jpg",
    "Pastel" to "https://upload.wikimedia.org/wikipedia/commons/b/b3/Pastel_Curry_Puff.jpg",
    "Kue Cubit" to "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Kue_cubit.jpg/1024px-Kue_cubit.jpg",
    "Serabi" to "https://upload.wikimedia.org/wikipedia/commons/f/f0/Serabi_Solo.jpg",
    "Terang Bulan" to "https://upload.wikimedia.org/wikipedia/commons/7/7b/Terang_Bulan.jpg",

    // === DRINKS ===
    "Es Teh" to "https://images.pexels.com/photos/1193335/pexels-photo-1193335.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Es Jeruk" to "https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Kopi" to "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Jus Alpukat" to "https://upload.wikimedia.org/wikipedia/commons/d/d9/Avocado_smoothie.jpg",
    "Es Campur" to "https://upload.wikimedia.org/wikipedia/commons/a/a2/Es_Campur_Jakarta.jpg",
    "Cendol" to "https://upload.wikimedia.org/wikipedia/commons/4/47/Es_Cendol_Bandung.jpg",
    "Teh Tarik" to "https://upload.wikimedia.org/wikipedia/commons/6/6c/Teh_Tarik.jpg",
    "Susu" to "https://images.pexels.com/photos/544113/pexels-photo-544113.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === FRUITS ===
    "Pisang" to "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Mangga" to "https://images.pexels.com/photos/2294471/pexels-photo-2294471.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Jeruk" to "https://images.pexels.com/photos/327098/pexels-photo-327098.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Apel" to "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Semangka" to "https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Pepaya" to "https://images.pexels.com/photos/3568039/pexels-photo-3568039.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Nanas" to "https://images.pexels.com/photos/227432/pexels-photo-227432.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Durian" to "https://images.pexels.com/photos/5945760/pexels-photo-5945760.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === FAST FOOD: KFC ===
    "KFC Original" to "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800",
    "KFC Crispy" to "https://images.pexels.com/photos/2232433/pexels-photo-2232433.jpeg?auto=compress&cs=tinysrgb&w=800",
    "KFC Combo Attack" to "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=800",
    "KFC Chicken Wings" to "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-spicy-60616.jpeg?auto=compress&cs=tinysrgb&w=800",
    "KFC Rice" to "https://images.pexels.com/photos/3926123/pexels-photo-3926123.jpeg?auto=compress&cs=tinysrgb&w=800",
    "KFC Pergedel" to "https://upload.wikimedia.org/wikipedia/commons/7/7b/Perkedel_kentang.JPG",
    "KFC Coleslaw" to "https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === FAST FOOD: MCD ===
    "McD Big Mac" to "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD McChicken" to "https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD Cheeseburger" to "https://images.pexels.com/photos/1251198/pexels-photo-1251198.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD Double Cheeseburger" to "https://images.pexels.com/photos/2983101/pexels-photo-2983101.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD PaNas 1" to "https://images.pexels.com/photos/2960569/pexels-photo-2960569.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD AyaGulai" to "https://upload.wikimedia.org/wikipedia/commons/4/4c/Lontong_Opor.jpg",
    "McD McFlurry" to "https://images.pexels.com/photos/10321286/pexels-photo-10321286.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD French Fries M" to "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD Sundae" to "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === FAST FOOD: BURGER KING ===
    "BK Whopper" to "https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=800",
    "BK Whopper Jr" to "https://images.pexels.com/photos/1639556/pexels-photo-1639556.jpeg?auto=compress&cs=tinysrgb&w=800",
    "BK Chicken Royale" to "https://images.pexels.com/photos/1199959/pexels-photo-1199959.jpeg?auto=compress&cs=tinysrgb&w=800",
    "BK Onion Rings" to "https://images.pexels.com/photos/10502157/pexels-photo-10502157.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === CAFE: STARBUCKS ===
    "Starbucks Caramel Macchiato" to "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Latte" to "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Cappuccino" to "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Americano" to "https://images.pexels.com/photos/6347/coffee-cup-working-happy.jpg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Frappuccino" to "https://images.pexels.com/photos/1233519/pexels-photo-1233519.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Green Tea Latte" to "https://images.pexels.com/photos/2947690/pexels-photo-2947690.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Starbucks Java Chip" to "https://images.pexels.com/photos/2035066/pexels-photo-2035066.jpeg?auto=compress&cs=tinysrgb&w=800",

    // === CAFE: CHATIME & OTHERS ===
    "Chatime Pearl Milk Tea" to "https://images.pexels.com/photos/3625299/pexels-photo-3625299.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Chatime Hazelnut Chocolate" to "https://images.pexels.com/photos/4666999/pexels-photo-4666999.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Chatime Taro Milk Tea" to "https://images.pexels.com/photos/5947019/pexels-photo-5947019.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Chatime Mango Green Tea" to "https://images.pexels.com/photos/5947012/pexels-photo-5947012.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Chatime Matcha Milk Tea" to "https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Kopi Kenangan Mantan" to "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Kopi Kenangan Signature" to "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Kopi Susu Tetangga" to "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Es Kopi Susu" to "https://images.pexels.com/photos/1235706/pexels-photo-1235706.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Avocado Coffee" to "https://images.pexels.com/photos/4109728/pexels-photo-4109728.jpeg?auto=compress&cs=tinysrgb&w=800",
    
    // === REGIONAL SPECIALTIES ===
    "Mie Aceh" to "https://upload.wikimedia.org/wikipedia/commons/7/7b/Mie_Aceh_Goreng.jpg",
    "Kuah Pliek U" to "https://upload.wikimedia.org/wikipedia/commons/e/ea/Kuah_Pliek_U.jpg",
    "Sate Padang" to "https://upload.wikimedia.org/wikipedia/commons/a/a2/Sate_Padang.jpg",
    "Gulai Kepala Ikan" to "https://upload.wikimedia.org/wikipedia/commons/3/3c/Gulai_Kepala_Ikan_Kakap.JPG",
    "Dendeng Batokok" to "https://upload.wikimedia.org/wikipedia/commons/4/4c/Dendeng_Batokok.jpg",
    "Gulai Cubadak" to "https://upload.wikimedia.org/wikipedia/commons/f/f3/Gulai_Nangka_Muda.jpg",
    "Asam Padeh" to "https://upload.wikimedia.org/wikipedia/commons/0/07/Asam_Padeh_Tongkol.jpg",
    "Pempek Palembang" to "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pempek_Palembang.jpg",
    "Tekwan" to "https://upload.wikimedia.org/wikipedia/commons/2/22/Tekwan_Palembang.JPG",
    "Model" to "https://upload.wikimedia.org/wikipedia/commons/e/e6/Model_Ikan_Palembang.JPG",
    "Nasi Liwet" to "https://upload.wikimedia.org/wikipedia/commons/8/87/Nasi_Liwet_Solo.jpg",
    "Gudeg" to "https://upload.wikimedia.org/wikipedia/commons/0/0e/Nasi_Gudeg.jpg",
    "Nasi Pecel" to "https://upload.wikimedia.org/wikipedia/commons/6/6f/Nasi_Pecel.jpg",
    "Rujak Cingur" to "https://upload.wikimedia.org/wikipedia/commons/8/83/Rujak_Cingur_Surabaya.jpg",
    "Tahu Campur" to "https://upload.wikimedia.org/wikipedia/commons/a/a5/Tahu_Campur_Lamongan.JPG",
    "Lontong Balap" to "https://upload.wikimedia.org/wikipedia/commons/b/b3/Lontong_Balap_Surabaya.jpg",
    "Sate Klatak" to "https://upload.wikimedia.org/wikipedia/commons/5/53/Sate_Klatak_Jogja.jpg",
    "Sego Tempong" to "https://upload.wikimedia.org/wikipedia/commons/a/a9/Nasi_Tempong_Banyuwangi.jpg",
    "Nasi Gandul" to "https://upload.wikimedia.org/wikipedia/commons/2/25/Nasi_Gandul.jpg",
    "Tahu Tek" to "https://upload.wikimedia.org/wikipedia/commons/9/9f/Tahu_Tek_Surabaya.JPG",
    "Nasi Krawu" to "https://upload.wikimedia.org/wikipedia/commons/2/23/Nasi_Krawu_Gresik.jpg",
    "Soto Lamongan" to "https://upload.wikimedia.org/wikipedia/commons/a/a9/Soto_Lamongan.jpg",
    "Babi Guling" to "https://upload.wikimedia.org/wikipedia/commons/f/f9/Babi_guling_Bali.jpg",
    "Sate Lilit" to "https://upload.wikimedia.org/wikipedia/commons/9/91/Sate_Lilit_Bali.jpg",
    "Ayam Betutu" to "https://upload.wikimedia.org/wikipedia/commons/f/fe/Ayam_Betutu_Khas_Bali.jpg",
    "Lawar" to "https://upload.wikimedia.org/wikipedia/commons/6/67/Lawar_Bali.jpg",
    "Nasi Jinggo" to "https://upload.wikimedia.org/wikipedia/commons/3/30/Nasi_Jinggo.jpg",
    "Se'i Sapi" to "https://upload.wikimedia.org/wikipedia/commons/1/1a/Sei_Sapi_NTT.jpg",
    "Coto Makassar" to "https://upload.wikimedia.org/wikipedia/commons/9/9c/Coto_Makassar.jpg",
    "Pallubasa" to "https://upload.wikimedia.org/wikipedia/commons/9/95/Pallubasa.jpg",
    "Konro" to "https://upload.wikimedia.org/wikipedia/commons/1/1c/Sop_Konro.jpg",
    "Pisang Epe" to "https://upload.wikimedia.org/wikipedia/commons/a/a5/Pisang_Epe_Makassar.jpg",
    "Kapurung" to "https://upload.wikimedia.org/wikipedia/commons/5/5b/Kapurung_Palopo.jpg",
    
    // === INTERNATIONAL ===
    "Avocado Toast" to "https://images.pexels.com/photos/1656666/pexels-photo-1656666.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Egg Omelet" to "https://images.pexels.com/photos/3026805/pexels-photo-3026805.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Pancakes" to "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Salad" to "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Burger" to "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Pizza" to "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Pasta" to "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Fried Rice" to "https://images.pexels.com/photos/2092916/pexels-photo-2092916.jpeg?auto=compress&cs=tinysrgb&w=800",
    "Fried Chicken" to "https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&w=800",
    "McD Ayam Gulai" to "https://upload.wikimedia.org/wikipedia/commons/3/3c/Gulai_Ayam.jpg"
)
